//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeYourRestaurant.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meal()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TimeId { get; set; }
        public Nullable<int> PriceId { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public Nullable<bool> BestFood { get; set; }
        public string Photo { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Time { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Price Price1 { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual Time Time1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLine> OrderLines { get; set; }
    }
}
