//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeYourRestaurant___Main.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        public int ID { get; set; }
        public Nullable<int> ticketId { get; set; }
        public Nullable<int> MealId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> Done { get; set; }
    
        public virtual Meal Meal { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
