//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeYourRestaurant___Main.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRCode
    {
        public int ID { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public Nullable<int> TableNumber { get; set; }
        public string Photo { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
