//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeYourRestaurant___Order.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
