//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeYourRestaurant___Order.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> MealId { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Meal Meal { get; set; }
        public virtual Order Order { get; set; }
    }
}
