//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeYourRestaurant___Received.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meal()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TimeId { get; set; }
        public Nullable<int> PriceId { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public Nullable<bool> BestFood { get; set; }
        public string Photo { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Time { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Price Price1 { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual Time Time1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLine> OrderLines { get; set; }
    }
}
